- MPChartLib/src/com/github/mikephil/charting/utils/Legend.java
The (x, y) is start point of the form, but not center
> Fix wrong position of linear legend form

- MPChartLib/build.gradle
- build.gradle
With android-maven plugin MPAndroidChart can now be installed in the local maven repository:
gradle install
In addition its now possible to get it as a maven dependency: https://jitpack.io/#jitpack/MPAndroidChart/v1.7.5 : )
> Added android-maven plugin

- MPChartExample/build.gradle
- MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
- MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java
- MPChartLib/src/com/github/mikephil/charting/renderer/RadarChartRenderer.java
I want to override how PieChartRenderer's center text is drawn, but since drawCenterText is private, I can't do anything.
I've modified all *drawXXX()* invoked from *drawExtras()*, which were the ones declared as private.
Also, I've upgraded the example buildTools, which was still set to 19.0.0, whereas the library was already using 21.1.1
> Change Rendeder's access level modifiers for extra draw methods

- MPChartLib/src/com/github/mikephil/charting/data/DataSet.java
There are cases that we want to provide xVals and yVals arrays from the cache, and we want to have the same references for the xVals and yVals arrays, there were no problem with xVals, but there were cases when yVals created again and we loose reference with it, this pull request separates two conditions, thus preventing create yVals when it is not null.
> Stable reference for the yVals array

- MPChartExample/src/com/xxmassdeveloper/mpchartexample/notimportant/MainActivity.java
- MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
- MPChartLib/src/com/github/mikephil/charting/charts/PieRadarChartBase.java
- MPChartLib/src/com/github/mikephil/charting/listener/BarLineChartTouchListener.java
- MPChartLib/src/com/github/mikephil/charting/listener/PieRadarChartTouchListener.java
- MPChartLib/src/com/github/mikephil/charting/utils/Utils.java
- MPChartLib/src/com/github/mikephil/charting/utils/ViewPortHandler.java
You should test this for performance!
Anyway I've looked at the `OverScroll` (API>=16) implementation, and Google says that to work with it you need to `postInvalidateOnAnimation()` and listen to `computeScroll()`.
The `OverScroll` is API 16 and is a bit of an overkill and meant for views, so I haven't used it, but used the same mechanism (`postInvalidateOnAnimation`/`computeScroll`).
If we will want to support bounce on edges, we will need to support it in the viewport and maybe in the renderers. `OverScroll` is meant to do that on `View`s only...
Also I've used `VelocityTracker` (which is used by the Fling recognizer) because we are not tracking fling but tracking sequential movement for panning. So android supplies the velocity arguments in the wrong listener but at least the …
> Deceleration after dragging in Line and Pie/Radar charts

- MPChartLib/src/com/github/mikephil/charting/utils/LargeValueFormatter.java
Now, for adding a dollar-sign to yAxis (for example) we need only use a non default constructor of ```LargeValueFormatter```:
```java
yAxis.setValueFormatter(new LargeValueFormatter("$"));
```
> Large value formatter now can appends a specified text to the result string

- MPChartLib/src/com/github/mikephil/charting/components/Legend.java
- MPChartLib/src/com/github/mikephil/charting/renderer/LegendRenderer.java
- MPChartLib/src/com/github/mikephil/charting/utils/Utils.java
Line spacing is used correctly now.
Previously there was use of YEntrySpace, but now we are taking the correct line spacing, and defaulting YEntrySpace to 0.
To solve the legend form alignment issue to the text line - I still used a text height calculation, as some fonts (namely the Open Sans) do not have the "A" stretched from ascent to descent, but do have other letters ("J", "Q", "`") going out into the ascent or descent area. So calculating size of ABC instead of AJQ seems to be better in that matter. Taking half an A back from the baseline - is a good middle point for the form center.
> Improvements to legend drawing

- MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
- MPChartLib/src/com/github/mikephil/charting/charts/PieRadarChartBase.java
- MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
- MPChartLib/src/com/github/mikephil/charting/renderer/ScatterChartRenderer.java
They disappeared because of NaN values introduces in the previous iteration, when the previous dataset does not contain a yValue for that specific index.
(And a little refactoring to make this thing consistent across all appearances)
> Fixed an issue where highlights disappear on multi-datasets

- MPChartLib/src/com/github/mikephil/charting/data/ChartData.java
- MPChartLib/src/com/github/mikephil/charting/data/DataSet.java
Float.MIN_VALUE is not the minimum... -Float.MIN_VALUE is!
And of course we need to also account for a case where we are looping over zero elements.
> Fixed a crash after matrix transformation when only one bar is visible

- MPChartLib/src/com/github/mikephil/charting/data/DataSet.java
When deserializing an object from this lib that contains a ValueFormatter member variable, Gson throws an exception. And since there is a ValueFormatter variable in DataSet, and ChartData uses DataSet, this affects many objects. I came across it deserializing my object which contained a PieChart using mGson.fromJson(myJsonString, MyPieChartObject.class);. Making an instance creator as Gson suggested did not solve the problem.
To fix this all I did was make the mValueFormatter transient so it does not get serialized by Gson, and therefore does not throw the exception. It works like a charm, and hopefully shouldn't affect anything negatively.
Before:
(Stack trace)
```
1265-1265/com.example.test E/AndroidRuntime﹕ FATAL EXCEPTION: main
Process: com.example.test, PID: 1265 …
```
> Do not serialize ValueFormatter interface member variable

- MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
- MPChartLib/src/com/github/mikephil/charting/charts/RadarChart.java
- MPChartLib/src/com/github/mikephil/charting/renderer/YAxisRendererRadarChart.java
* `startAtZeroEnabled` should not actually start at zero when there are negative values, as these will be unaccessible
* In radar charts, when values are drawn below zero, they are actually draw in another x-index as it is a circular chart. So no we handle that correctly in (hopefully) all cases of `startAtZeroEnabled` = true/false
> Fixes for the y axis with negative values

- MPChartLib/src/com/github/mikephil/charting/charts/CombinedChart.java
This fixes https://github.com/danielgindi/ios-charts/issues/323
> Fixes an issue with X min/max in combined charts without bubble data

- MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
If you have two values that are at separated by a large number of empty x-vals in between and you pinch to zoom inwards, eventually the line between them is not drawn. This is because the two `DataSet.getEntryForXIndex` calls may return the same `Entry`. The fix is to try and modify the min and max values to accommodate drawing a single line, rather than no line.
> Fix disappearing line when zooming into LineChart

- MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
- MPChartLib/src/com/github/mikephil/charting/charts/PieRadarChartBase.java
Instead of zeroing the minOffset and losing the ability to add it - now we can control it manually if needed, and still defaults to 0...
> Allow getting/settings minOffset of the charts

- MPChartLib/src/com/github/mikephil/charting/charts/Chart.java
It's not necessarily highlighting a "touch", it receives a highlight object. Times have changed :-)
> Moved highlightTouch logic to highlightValue & deprecated highlightTouch

- MPChartLib/src/com/github/mikephil/charting/data/DataSet.java
- MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
I tried to fix this issue in 92ea5b3, but it looks like it didn't cover all issues. The initial issue was that `getEntryForXIndex()` was returning the same `Entry`, but the deeper reason is that it is doing so because it rounds the x-index to the *nearest* one if there is no entry at that specific index. Both calls were getting rounded to the same x-index.
To avoid this scenario, `getEntryIndex(int)` has been overloaded to take in a parameter that defines which way to round the index if it is not found. The default is to keep the original behavior, but the LineChartRenderer needs to make sure that the two entries are rounded away from each other, so that the lines extend *at least* as far as the viewport bounds.
> Fixed rounding issue with LineChartRenderer

- MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java
It was "insetting" by a factor of 100,
because of wrong perception of the percentage property.
> Fixed bounding rect for pie center text

- MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java
Passing a Paint object as the 4th argument to `drawBitmap` will draw the entire canvas with transparency if the last color used was transparent.
We can pass null instead.
http://developer.android.com/reference/android/graphics/Canvas.html#drawBitmap(android.graphics.Bitmap, float, float, android.graphics.Paint)
> Fixes #1258

- MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java
I think that the pie chart's rotationAngle should not be multiplied by the mAnimation.getPhaseY(). This means that animated segments grow outwards from the rotationAngle rather than always from 0 degrees.
Do you agree?
> Pie animation should be applied after rotationAngle

- MPChartExample/src/com/xxmassdeveloper/mpchartexample/CombinedChartActivity.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/CubicLineChartActivity.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/DrawChartActivity.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/DynamicalAddingActivity.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/InvertedLineChartActivity.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivity1.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivity2.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivityColored.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/ListViewMultiChartActivity.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/MultiLineChartActivity.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/RealtimeLineChartActivity.java
- MPChartExample/src/com/xxmassdeveloper/mpchartexample/fragments/SimpleFragment.java
- MPChartLib/src/com/github/mikephil/charting/data/LineDataSet.java
- MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmLineDataSet.java
- MPChartLib/src/com/github/mikephil/charting/interfaces/datasets/ILineDataSet.java
- MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
Kept the old functions for compatibility - but marked as Deprecated.
> Renamed "circle size" to "circle radius", deprecated set/getCircleSize

- MPChartLib/src/com/github/mikephil/charting/charts/PieChart.java
- MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java
Fixed the default percentage value, and added the clipping that I wanted to do long ago and now it is finally documented in Google's docs that clipping is supported for API 18 so I did it :-)
I think this can go in for the 2.2.2 version
> Pie center text

- MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
I’ve added a flag (keepPositionOnRotation) to BarLineChartBase
indicating whether the chart
should stay at its current position or not.
This is the same feature as described in the PR on [ios-charts](https://github.com/danielgindi/ios-charts/pull/824)
In the examples this feature doesn't work properly, because the Activities get reloaded on every rotation. This can be turned of be adding `    <activity android:name="BarChartActivity"
android:configChanges="keyboardHidden|orientation|screenSize"></activity>` in the AppManifest.
> Keep position on rotation

- MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
Since lately we've done many fixes to the calculation for first/last
points in cubic drawing - we not do not need that first "add curve".
Related issue: https://github.com/danielgindi/ios-charts/issues/683
> Fixed cubic line "leak" on first point.

- MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java
If the user provides data that does not allow the spacing to stay even -
he will need to manually fix that (i.e by giving a larger inner hole)
Even with a hole - with very small slices it will not help.
Spacing could be reduces, and small slices can be removed from the dataset.
> Do not let slice spacing make the chart go haywire. (Fixes #1582)

- MPChartLib/src/com/github/mikephil/charting/charts/PieChart.java
Remove call to super.calcMinMax() in PieChart.
In the PieChart, the method:
protected void calcMinMax() {
super.calcMinMax();
calcAngles();
}
Calls the parent's method, which is in PieRadarChartBase:
protected void calcMinMax() {
mXAxis.mAxisRange = mData.getXVals().size() - 1;
}
This gives an error, because in the init section of the PieChart, mAxis is set to null.
My proposed fix would be to remove the call to the parent's calcMinMax method, but I am not deep enough into the framework to decide if that's a good idea.
> Attempt to fix issue #1622

- MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
- MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java
The test were performed by manually opening and closing line chart (or pie chart) as fast as possible in a loop
Results before changes:
Results after changes:
I don't know which code change contributed more, setting canvas to null or calling gc
> potential solution to rare out of memory problems

- MPChartExample/src/com/xxmassdeveloper/mpchartexample/AnotherBarActivity.java
- MPChartLib/src/com/github/mikephil/charting/utils/Utils.java
hello, this is because the size of the letters are not the same. The return of getTextBounds method for String Mar 30 and 01 Apr.
Before
After
> [Resolved] X Axis Labels being cut off horizontally #1657 

- MPChartLib/src/main/java/com/github/mikephil/charting/renderer/LineChartRenderer.java
The LineChartRenderer didn't use x values to draw the cubic fill, but the x indices instead. This problem is fixed by my commit.
> Fixed Bug in LineChartRenderer

- MPChartLib/src/main/java/com/github/mikephil/charting/components/ComponentBase.java
The documentation is currently misleading, stating the setTextSize set the size in pixel, when it actually expect a dimension in density pixels.
This addresses this issue.
> Correct documentation for ComponentBase#setTextSize

- MPChartLib/src/main/java/com/github/mikephil/charting/renderer/PieChartRenderer.java
This fix is so small values won't appear as "background" (which really is a huge circle) when slice space is used.
I've found out that because sweepAngleOuter is negative it gets set to 0 which then causes arcStartPointX and arcStartPointY not to be set. Both arcStartPointX and arcStartPointY are used in calculateMinimumRadiusForSpacedSlice which calculates huge negative value because of that, which is then turned into huge positive value in the next line.
In the end we end up with a tiny value creating huge circle that looks like a background.
> Pie chart, fix for small values appearing as background

- MPChartLib/build.gradle
Fix https://github.com/PhilJay/MPAndroidChart/issues/2813 by setting [javadoc character encoding to utf8](http://stackoverflow.com/a/25917146/1413900 ).
> Set javadoc character encoding to utf8

- gradlew
https://github.com/PhilJay/MPAndroidChart/issues/2805
> fix tests for java executable location in gradlew to be compatible with bash 4.3.42

- MPChartLib/src/main/java/com/github/mikephil/charting/components/ComponentBase.java
The default text size in ComponentBase was defined as 10px instead of 10dp, which caused tiny text rendering and did not reflect the javadoc or the general behavior of setTextSize(...).
> Fix for default text size being set in PX instead of DP

- MPChartLib/src/main/java/com/github/mikephil/charting/renderer/LineChartRenderer.java
**Issue (#2620) :**
When using multiple LineDataSets like the follows:
int solidColor = 0xFFFF00FF;
dataSet.setColor(solidColor);
dataSet.setCircleColor(solidColor);
int semiTransparentColor = 0x8A000000;
fadedSet.setColor(semiTransparentColor);
LineData data = new LineData(dataSet, fadedSet);
the circles in `dataSet` will rendered with the alpha from `fadedSet` (`0x8A`).
The reason for this is that `mRenderPaint` is not reset properly before drawing the circles. The first time `drawCircles(...)` is called the `imageCache.fill(...)` method is used where the color is set by `mRenderPaint.setColor(set.getCircleColor(i))`, restoring the alpha to `0xFF`. The second time homever, `imageCache.fill(...)` is not called which means that `mRenderPaint` will use it's old color/alpha, which in this …
> Fix circles inherit alpha #2620

- MPChartLib/src/main/java/com/github/mikephil/charting/components/AxisBase.java
> Fixed docs typo in AxisBase.java

- MPChartExample/src/com/xxmassdeveloper/mpchartexample/PiePolylineChartActivity.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/PieDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/interfaces/datasets/IPieDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/renderer/PieChartRenderer.java
Fixes: #3897
If `dataSet.setUsingSliceColorAsValueLineColor(true);` is called, value line color will be the same color with slice.
> PieChart: Add option for using slice color as value line color

- MPChartExample/build.gradle
- MPChartLib/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This PR updates to most recent stable Android Studio 3.1.2
> update to Android Studio 3.1.2

- MPChartLib/src/main/java/com/github/mikephil/charting/renderer/LineChartRenderer.java
- MPChartLib/src/main/java/com/github/mikephil/charting/renderer/PieChartRenderer.java
Even if the WeakReference field is not null, the contained value may be null.  Additionally, you always need a strong reference to the value to ensure it isn't garbage collected while you're using it.
This should fix #3007.
> Fix some potential NPEs with WeakReference usage

- MPChartLib/src/main/java/com/github/mikephil/charting/components/YAxis.java
I noticed that while trying to add spacing to the bottom of a chart, to allow for the interior labels enough room that they don't overlap the data, nothing was happening. I was confused as to why setting the bottom spacing was doing literally nothing, and discovered it was disabled if the min was manually changed.
I thought it strange to disable this without mentioning anywhere in the documentation that this behavior was intentional. Adding percentage based padding let's developers easily add this extra space, but disabling it doesn't make sense. If developers don't want that extra spacing, they'll do what they would've done anyway, set the spacing to 0, as the default is 10%.
Since this behavior of disabling the spacing if custom values are set, even though the calculated range is BASED …
> Remove YAxis Custom Min/Max Check for Padding

- MPChartLib/src/main/java/com/github/mikephil/charting/jobs/AnimatedZoomJob.java
The zoomAndCenterAnimated method in BarLineChartBase crashes with a NullPointer exception because the yAxis variable is null when onAnimationUpdate is called. The yAxis is null because of missing setters in the getInstance method of AnimatedZoomJob.
> Fix for missing setters in getInstance method

- MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivityColored.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/BarDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/BarLineScatterCandleBubbleDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/BaseDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/BubbleDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/CandleDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/DataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/LineDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/LineRadarDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/LineScatterCandleRadarDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/PieDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/RadarDataSet.java
- MPChartLib/src/main/java/com/github/mikephil/charting/data/ScatterDataSet.java
Issue has already been created where the problem: [#1604]
Copying data sets methods were missing some fields. I refactored the way data sets are copied and added missing fields.
> Update and reorganise copy data sets methods (Fix for #1604).

- MPChartLib/src/main/java/com/github/mikephil/charting/components/YAxis.java
I need to be able to set some restriction on autoscale so I keep autoscale working but also make sure that certain range is always visible.
Tried to do it in the way the rest of the API is done and with as limited changes as possible.
> Option to set restrictions for Y axis autoscaling.

- MPChartLib/src/main/java/com/github/mikephil/charting/charts/BarLineChartBase.java
Fix for #2369.
Modified the code as described in Issue #2369 to see, that the issue still exists.
Checked against different positions of Legend (TOP, BOTTOM).
No need for that, I think.
Issue #2369
Removed statements described in ticket as they were completely not needed. Calculating offsets is already done in `BarLineCharBase#calculateOffsets(...)` (`calculateLegendOffsets(...)` is called inside it).
The code, where calculating legend offset is done in [`BarChartLineBase#473`](https://github.com/PhilJay/MPAndroidChart/compare/master...RobertZagorski:bugfix/%232369-legend-offset-is-not-calculated-twice-for-line-chart?expand=1#diff-c2688ad7111a70de6e0354d19bbff337R473)
Modified temporarily `LineChartActivity1` code to reproduce the issue and tested against various legend positions. …
> Remove mLabelRotatedHeight counted twice, when calculating legend offset

- MPChartLib/src/main/java/com/github/mikephil/charting/charts/BarLineChartBase.java
- MPChartLib/src/main/java/com/github/mikephil/charting/components/AxisBase.java
> Add option to draw limit lines on top of data

- MPChartLib/src/main/java/com/github/mikephil/charting/components/MarkerImage.java
`mDrawable` is already checked for `null` in line 138 of the `draw(...)` method:
`if (mDrawable == null) return;`
> Remove nullcheck for known non-null variable

- MPChartLib/src/main/java/com/github/mikephil/charting/formatter/PercentFormatter.java
- [-] I have added/updated examples and tests for any new behavior.
This PR makes the space between the number and the percent sign in PercentFormatter optional.
It preserves the current behaviour (insert space) as default but allows for not inserting the space.
As there is no definite convention on wether to insert a space or not, the user should imho have the opportunity to choose.
> PercentFormatter: make space between number and percent sign optional

- MPChartLib/src/main/java/com/github/mikephil/charting/renderer/BarChartRenderer.java
- MPChartLib/src/main/java/com/github/mikephil/charting/renderer/HorizontalBarChartRenderer.java
fix NPE when use solid color with barchart
```
2020-02-07 18:01:27.307 10747-10747/com.xxmassdeveloper.mpchartexample E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.xxmassdeveloper.mpchartexample, PID: 10747
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
at com.github.mikephil.charting.renderer.BarChartRenderer.drawDataSet(BarChartRenderer.java:147)
at com.github.mikephil.charting.renderer.BarChartRenderer.drawData(BarChartRenderer.java:81)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:242)
at android.view.View.draw(View.java:20617)
at android.view.View.updateDisplayListIfDirty(View.java:19449)
at android.view.View.draw(View.java:20330)
at …
```
> fix NPE when use solid color with barchart
