PhilJay/MPAndroidChart

MPChartLib/src/com/github/mikephil/charting/charts/Chart.java

This fixes an IllegalArgumentException (issue #262) when creating the draw bitmap with width/height of 0.  This is a valid case and also happens when using the include xml tag to include a layout that contains a chart.

Fixes Issue #262 where it throws an exception when using the include xml tag

---

Projects_using_MPAndroidChart.txt

Hey Phil, Thanks to your library! It is an awesome charting solution for Android.

Health Infinity loves MPAndroidChart

---

MPChartLib/src/com/github/mikephil/charting/charts/RadarChart.java

- In the Android Studio Preview mode, mData is null and throws an exception.

Fixed null pointer exception in design view (issue #370)

---

MPChartExample/res/menu/combined.xml
MPChartExample/src/com/xxmassdeveloper/mpchartexample/CombinedChartActivity.java

DataSets depend on different YAxis. Added a menu to toggle values and YAxis dependency.
I've messed the formatting a little bit (only CombinedChartActivity.java), I hope you use some kind of autoformatter.

Improved CombinedChart example

---

MPChartLib/src/com/github/mikephil/charting/charts/BarChart.java
MPChartLib/src/com/github/mikephil/charting/charts/CombinedChart.java

Fixes issue https://github.com/PhilJay/MPAndroidChart/issues/453

Change drawBarShadow default value to false

---

MPChartLib/src/com/github/mikephil/charting/charts/Chart.java

This will allow a proper flow of code- configuring and then setting data and rendering

Allow configuring the legend before setting data

---

MPChartLib/src/com/github/mikephil/charting/listener/BarLineChartTouchListener.java
MPChartLib/src/com/github/mikephil/charting/renderer/BarChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/HorizontalBarChartRenderer.java

Fixing some issues with inverted axis due to latest code changes

Inverted axis bugs

---

MPChartLib/src/com/github/mikephil/charting/components/AxisBase.java
MPChartLib/src/com/github/mikephil/charting/renderer/XAxisRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/YAxisRenderer.java

An option to enable dashed path effect for the YAxis and XAxis grid lines
```java
XAxis bottomAxis = chart.getXAxis();
...
bottomAxis.enableGridDashedLine(4.0f, 4.0f, 0);
bottomAxis.setGridLineWidth(1.0f);
```

Implement dash path effect for the grid lines

---

MPChartLib/src/com/github/mikephil/charting/data/CandleDataSet.java
MPChartLib/src/com/github/mikephil/charting/renderer/CandleStickChartRenderer.java

Implemented customizing colors and paint styles for increasing and decreasing candle entries.
Picture 1. Using setColor as before, and nothing changed, so this is a backward compatible pull request (There are a lot of apps using MPAndroidChart, and I don't want to break existing apps :) )
```java
CandleDataSet set1 = new CandleDataSet(yVals1, "Data Set");
set1.setAxisDependency(AxisDependency.LEFT);
set1.setColor(Color.rgb(80, 80, 80));
```
Picture 2. New methods for customizing
```java
CandleDataSet set1 = new CandleDataSet(yVals1, "Data Set");
set1.setAxisDependency(AxisDependency.LEFT);
set1.setColor(Color.parseColor("#aade87"));
set1.setDecreasingColor(Color.parseColor("#ffd5d5"));
set1.setDecreasingPaintStyle(Paint.Style.FILL);
set1.setShadowColor(Color.parseColor("#c48e50"));
``` …

Implement customizing colors and paint styles for increasing and decreasing candle entries

---

MPChartLib/src/com/github/mikephil/charting/buffer/CandleBodyBuffer.java
MPChartLib/src/com/github/mikephil/charting/buffer/CandleShadowBuffer.java
MPChartLib/src/com/github/mikephil/charting/buffer/CircleBuffer.java
MPChartLib/src/com/github/mikephil/charting/buffer/LineBuffer.java
MPChartLib/src/com/github/mikephil/charting/data/DataSet.java
MPChartLib/src/com/github/mikephil/charting/renderer/CandleStickChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/Renderer.java
MPChartLib/src/com/github/mikephil/charting/utils/Transformer.java

Fixes some bugs during animations

Line viewport range fix

---

MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
MPChartLib/src/com/github/mikephil/charting/components/AxisBase.java
MPChartLib/src/com/github/mikephil/charting/components/LimitLine.java
MPChartLib/src/com/github/mikephil/charting/components/YAxis.java
MPChartLib/src/com/github/mikephil/charting/renderer/AxisRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/XAxisRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/XAxisRendererHorizontalBarChart.java
MPChartLib/src/com/github/mikephil/charting/renderer/XAxisRendererRadarChart.java
MPChartLib/src/com/github/mikephil/charting/renderer/YAxisRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/YAxisRendererHorizontalBarChart.java

+ centerViewTo method for BarLineChartBase

LimitLine support for XAxis

---

MPChartExample/src/com/xxmassdeveloper/mpchartexample/PieChartActivity.java
MPChartLib/src/com/github/mikephil/charting/animation/ChartAnimator.java
MPChartLib/src/com/github/mikephil/charting/charts/Chart.java
MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/utils/AnimationEasing.java

Demonstrated in PieChartActivity
Animations are now supported on all Android versions

Support for animation easing functions

---

MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java

Fix cubic fill bug for the LineChart

---

README.md

* When using proguard and NOT whitelisting MPAndroidChart, some functionality
will break like animate methods.
Change-Id: If329842301eb41f7f713c1148b5ca364917e3d7a
Signed-off-by: Alexander Martinz <eviscerationls@gmail.com>

Readme: add notice about Proguard

---

MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
MPChartLib/src/com/github/mikephil/charting/charts/PieRadarChartBase.java
MPChartLib/src/com/github/mikephil/charting/charts/RadarChart.java
MPChartLib/src/com/github/mikephil/charting/components/Legend.java
MPChartLib/src/com/github/mikephil/charting/data/DataSet.java
MPChartLib/src/com/github/mikephil/charting/renderer/LegendRenderer.java

* Allow adding extra labels right after the auto calculated ones (usually used for totals etc.)
* Feature for completely custom legend labels/colors, and turn of the auto-calculation of the legend

Legend customization

---

MPChartLib/src/com/github/mikephil/charting/data/BarEntry.java

Fix stack size on values change

---

MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
MPChartLib/src/com/github/mikephil/charting/charts/HorizontalBarChart.java
MPChartLib/src/com/github/mikephil/charting/charts/PieChart.java
MPChartLib/src/com/github/mikephil/charting/charts/PieRadarChartBase.java
MPChartLib/src/com/github/mikephil/charting/charts/RadarChart.java
MPChartLib/src/com/github/mikephil/charting/components/Legend.java
MPChartLib/src/com/github/mikephil/charting/renderer/LegendRenderer.java
MPChartLib/src/com/github/mikephil/charting/utils/FSize.java
MPChartLib/src/com/github/mikephil/charting/utils/Utils.java

Currently supporting only the "below" legends - but is a great step towards it :-)
Just one note - it depends on the other PR https://github.com/PhilJay/MPAndroidChart/pull/698 so you will need to merge it first

Word wrapping legend

---

MPChartExample/src/com/xxmassdeveloper/mpchartexample/InvertedLineChartActivity.java
MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivity1.java
MPChartExample/src/com/xxmassdeveloper/mpchartexample/PerformanceLineChart.java
MPChartExample/src/com/xxmassdeveloper/mpchartexample/fragments/BarChartFrag.java
MPChartExample/src/com/xxmassdeveloper/mpchartexample/fragments/ComplexityFragment.java
MPChartExample/src/com/xxmassdeveloper/mpchartexample/fragments/ScatterChartFrag.java
MPChartExample/src/com/xxmassdeveloper/mpchartexample/fragments/SineCosineFragment.java
MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
MPChartLib/src/com/github/mikephil/charting/charts/Chart.java
MPChartLib/src/com/github/mikephil/charting/charts/PieChart.java
MPChartLib/src/com/github/mikephil/charting/charts/RadarChart.java
MPChartLib/src/com/github/mikephil/charting/data/ChartData.java
MPChartLib/src/com/github/mikephil/charting/data/DataSet.java
MPChartLib/src/com/github/mikephil/charting/renderer/BarChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/BubbleChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/CandleStickChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/RadarChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/ScatterChartRenderer.java

https://github.com/danielgindi/ios-charts/issues/114
By the way - highlightIndicatorEnabled had absolutely no meaning - but a duplicate of highlightEnabled...

Allow to `setHighlightEnabled` on a single DataSet

---

MPChartLib/src/com/github/mikephil/charting/data/DataSet.java
MPChartLib/src/com/github/mikephil/charting/renderer/RadarChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/YAxisRendererRadarChart.java

https://github.com/danielgindi/ios-charts/pull/152

Allow NaN values in Radar chart (Skip points)

---

MPChartLib/src/com/github/mikephil/charting/buffer/BarBuffer.java
MPChartLib/src/com/github/mikephil/charting/buffer/HorizontalBarBuffer.java

Testing for `mInverted` in the main `if` or inner `if` do not have a meaning performance-wise, as in both cases it's just one boolean check.

Removed duplicate code

---

Projects_using_MPAndroidChart.txt

Added a new project to the list that uses the following library.

Updated the list of projects

---

MPChartLib/src/com/github/mikephil/charting/charts/RadarChart.java
MPChartLib/src/com/github/mikephil/charting/renderer/RadarChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/XAxisRendererRadarChart.java

for Radarcharts with many entry's it would be nice to skip drawing some labels and weblines to get a nice presentation

added possibility to skip labels and WebLines in RadarChart

---

MPChartLib/src/com/github/mikephil/charting/renderer/BarChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/utils/Transformer.java

Try for example to highlight a negative value in the negative stacked bar chart, then animate on Y...

Fix highlight animation bug in stacked bar chart

---

MPChartLib/src/com/github/mikephil/charting/charts/LineChart.java
MPChartLib/src/com/github/mikephil/charting/charts/PieChart.java
MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java

Release Bitmap in LineChartRenderer and PieChartRenderer to avoid OOM issues.

Release Bitmap

---

MPChartLib/src/com/github/mikephil/charting/renderer/XAxisRenderer.java

It is now possible to overwrite drawing the line or label of the LimitLine

Make the XAxisRenderer more flexible

---

MPChartLib/src/com/github/mikephil/charting/data/Entry.java

As an Entry object may contain arbitrary data (in the form of a single object),
I took the route of checking if that object is also parcelable and parceling it
if so. If the object is not parcelable, then an Exception is thrown.

Make Entry class Parcelable.

---

MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java

Related to: https://github.com/danielgindi/ios-charts/pull/558

Fix for rounding error at the edges

---

MPChartLib/src/com/github/mikephil/charting/charts/BarChart.java
MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
MPChartLib/src/com/github/mikephil/charting/charts/Chart.java
MPChartLib/src/com/github/mikephil/charting/charts/HorizontalBarChart.java
MPChartLib/src/com/github/mikephil/charting/charts/PieChart.java
MPChartLib/src/com/github/mikephil/charting/charts/PieRadarChartBase.java
MPChartLib/src/com/github/mikephil/charting/charts/RadarChart.java

We can just check for mData being null,
knowing that this is the situation defined as "no data"

Removed ambiguity of mDataNotSet

---

MPChartLib/src/com/github/mikephil/charting/utils/Utils.java

Fixes for offset in line rendered through the rotation helper

Text lineheight fix

---

MPChartLib/src/com/github/mikephil/charting/charts/PieChart.java
MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java

Replaced them by a single method receiving CharSequence.

Remove PieChart.setCenterText() overloads.

---

MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java

Some improvements after that wonderful PR #1322

Pie animation fixes

---

MPChartLib/src/com/github/mikephil/charting/utils/Transformer.java

https://github.com/danielgindi/ios-charts/commit/9942aee9c424ba027e1e62079232d3dc5dcdf772

Prevent the matrix from reaching invalid values

---

MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java

Another one... The previous PR fixed the highlight - but not in  a case where the Pie was rotated.

Fixes base angle for rotate highlight in pie chart

---

MPChartLib/src/com/github/mikephil/charting/charts/BarChart.java
MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
MPChartLib/src/com/github/mikephil/charting/charts/Chart.java
MPChartLib/src/com/github/mikephil/charting/charts/CombinedChart.java
MPChartLib/src/com/github/mikephil/charting/charts/HorizontalBarChart.java

See also: https://github.com/danielgindi/ios-charts/pull/567

Make highlighter public for extensibility

---

MPChartLib/src/com/github/mikephil/charting/charts/PieChart.java
MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java

On large datasets - this will spare many loops over the data just to sum

Minor performance improvement

---

MPChartExample/res/menu/pie.xml
MPChartExample/res/menu/radar.xml
MPChartExample/src/com/xxmassdeveloper/mpchartexample/RadarChartActivitry.java
MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/RadarChartRenderer.java

And some fixes to pie animation along the way... We forgot to change the animation for values in pie chart

Radar animation

---

MPChartLib/src/com/github/mikephil/charting/charts/Chart.java

This is for the next version, let it sink in for a few days :-)

Center the "no data text" vertically

---

MPChartLib/src/com/github/mikephil/charting/charts/ScatterChart.java
MPChartLib/src/com/github/mikephil/charting/data/ScatterDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmScatterDataSet.java
MPChartLib/src/com/github/mikephil/charting/interfaces/datasets/IScatterDataSet.java
MPChartLib/src/com/github/mikephil/charting/renderer/ScatterChartRenderer.java

This is for the next version, let it sink in for a few days :-)

Scatter - support for shape holes, new X shape

---

MPChartLib/src/com/github/mikephil/charting/charts/PieChart.java
MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java

Xfer tricks not needed anymore - we only draw what we need!
That `PorterDuffXfer` thing just erases stuff. It does not really solve things.
Now we draw what we need so we don't need tricks.

Improvements for drawing pie slices

---

MPChartLib/src/com/github/mikephil/charting/charts/BarLineChartBase.java
MPChartLib/src/com/github/mikephil/charting/charts/RadarChart.java

This is related to this: https://github.com/danielgindi/ios-charts/issues/767

Fixed range calculation according to axisMin/axisMax

---

MPChartExample/AndroidManifest.xml
MPChartExample/src/com/xxmassdeveloper/mpchartexample/PiePolylineChartActivity.java
MPChartExample/src/com/xxmassdeveloper/mpchartexample/notimportant/MainActivity.java
MPChartLib/src/com/github/mikephil/charting/charts/PieRadarChartBase.java
MPChartLib/src/com/github/mikephil/charting/data/PieDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmPieDataSet.java
MPChartLib/src/com/github/mikephil/charting/interfaces/datasets/IPieDataSet.java
MPChartLib/src/com/github/mikephil/charting/renderer/PieChartRenderer.java

Labels around pie

---

MPChartExample/res/menu/line.xml
MPChartExample/src/com/xxmassdeveloper/mpchartexample/CubicLineChartActivity.java
MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivity1.java
MPChartExample/src/com/xxmassdeveloper/mpchartexample/LineChartActivity2.java
MPChartLib/src/com/github/mikephil/charting/data/DataSet.java
MPChartLib/src/com/github/mikephil/charting/data/LineDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmLineDataSet.java
MPChartLib/src/com/github/mikephil/charting/interfaces/datasets/ILineDataSet.java
MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java

https://github.com/danielgindi/Charts/issues/407

Horizontal cubic line

---

MPChartLib/src/com/github/mikephil/charting/charts/Chart.java
MPChartLib/src/com/github/mikephil/charting/charts/PieRadarChartBase.java
MPChartLib/src/com/github/mikephil/charting/data/ChartData.java
MPChartLib/src/com/github/mikephil/charting/data/CombinedData.java
MPChartLib/src/com/github/mikephil/charting/data/DataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/base/RealmBaseDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/base/RealmLineRadarDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmBarDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmBubbleDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmCandleDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmLineDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmPieDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmRadarDataSet.java
MPChartLib/src/com/github/mikephil/charting/data/realm/implementation/RealmScatterDataSet.java
MPChartLib/src/com/github/mikephil/charting/highlight/BarHighlighter.java
MPChartLib/src/com/github/mikephil/charting/highlight/ChartHighlighter.java
MPChartLib/src/com/github/mikephil/charting/highlight/CombinedHighlighter.java
MPChartLib/src/com/github/mikephil/charting/highlight/Highlight.java
MPChartLib/src/com/github/mikephil/charting/highlight/HorizontalBarHighlighter.java
MPChartLib/src/com/github/mikephil/charting/interfaces/datasets/IDataSet.java
MPChartLib/src/com/github/mikephil/charting/listener/ChartTouchListener.java
MPChartLib/src/com/github/mikephil/charting/listener/PieRadarChartTouchListener.java
MPChartLib/src/com/github/mikephil/charting/renderer/BubbleChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/CombinedChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/LineChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/ScatterChartRenderer.java
MPChartLib/src/com/github/mikephil/charting/utils/SelectionDetail.java
MPChartLib/src/com/github/mikephil/charting/utils/Utils.java

There are certain cases (ie. bubbles) which make sense to have multiple
values per xIndex.
This fixes that - and adds more granular highlight for Combined Chart.

Highlight enhancements

---

MPChartLib/src/com/github/mikephil/charting/components/ComponentBase.java
MPChartLib/src/com/github/mikephil/charting/renderer/LegendRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/XAxisRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/XAxisRendererHorizontalBarChart.java
MPChartLib/src/com/github/mikephil/charting/renderer/XAxisRendererRadarChart.java
MPChartLib/src/com/github/mikephil/charting/renderer/YAxisRenderer.java
MPChartLib/src/com/github/mikephil/charting/renderer/YAxisRendererHorizontalBarChart.java
MPChartLib/src/com/github/mikephil/charting/renderer/YAxisRendererRadarChart.java

I needed to add a style bold to my texts so added a property in ComponentBase mTextBold

Control on labels and legend_boldness

---

MPChartLib/src/main/java/com/github/mikephil/charting/components/AxisBase.java
MPChartLib/src/main/java/com/github/mikephil/charting/renderer/XAxisRenderer.java

I added method to allow dash effect on axis line, just like on iOS.
Also i added methods to set the ```DashPathEffect``` directly as i needed it.

AxisLine DashEffect

---

MPChartExample/AndroidManifest.xml
MPChartExample/src/com/xxmassdeveloper/mpchartexample/RadarChartActivity.java
MPChartExample/src/com/xxmassdeveloper/mpchartexample/notimportant/MainActivity.java

Fix typo "Activit**r**y" -> "Activity"

Rename RadarChartActivitry to RadarChartActivity

---

MPChartLib/build.gradle
build.gradle
gradle/wrapper/gradle-wrapper.properties

- [v] I have tested this extensively and it does not break any existing behavior.
- [v] I have added/updated examples and tests for any new behavior.
- [v] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]

Make MPAndroidChart compatible with Android Studio Iguana (2024)
